import { createHash } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
const tokensPath = join(root, "design/tokens/tokens.json");
const tokens = JSON.parse(await readFile(tokensPath, "utf8"));

const paletteKeys = [
  "background", "surface", "surface_strong", "border", "text", "muted", "subtle",
  "primary", "primary_strong", "danger", "danger_soft", "success", "success_soft",
  "warning", "warning_soft", "accent", "shadow",
];

function validateTokens(value) {
  if (value.schema_version !== 1) throw new Error("unsupported design token schema");
  if (!value.font?.sans) throw new Error("font.sans is required");
  for (const palette of ["light", "dark"]) {
    for (const key of paletteKeys) {
      if (typeof value[palette]?.[key] !== "string" || value[palette][key].length === 0) {
        throw new Error(`${palette}.${key} must be a non-empty string`);
      }
    }
  }
  for (const key of ["content", "theme"]) {
    if (typeof value.spacing?.[key] !== "string") throw new Error(`spacing.${key} is required`);
  }
  for (const key of ["control", "card", "panel"]) {
    if (typeof value.radius?.[key] !== "string") throw new Error(`radius.${key} is required`);
  }
}

function cssName(name) {
  return name.replaceAll("_", "-");
}

function paletteLines(palette) {
  return paletteKeys.map((key) => `  --sarmg-${cssName(key)}: ${palette[key]};`).join("\n");
}

function renderTokens() {
  return `/* Generated by scripts/build-design.mjs from design/tokens/tokens.json. */
@font-face {
  font-family: "ProjectSourceHanSans";
  src: local("Source Han Sans SC"), local("Source Han Sans CN"),
    local("Noto Sans CJK SC"), local("思源黑体");
  font-weight: 200 900;
  font-style: normal;
  font-display: swap;
}

.sarmg-theme {
  --sarmg-font-sans: ${tokens.font.sans};
${paletteLines(tokens.light)}
  --sarmg-content-gap: ${tokens.spacing.content};
  --sarmg-theme-gap: ${tokens.spacing.theme};
  --sarmg-radius-control: ${tokens.radius.control};
  --sarmg-radius-card: ${tokens.radius.card};
  --sarmg-radius-panel: ${tokens.radius.panel};
  color: var(--sarmg-text);
  background: var(--sarmg-background);
  font-family: var(--sarmg-font-sans);
  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
}

.sarmg-theme[data-sarmg-theme="dark"] {
  color-scheme: dark;
${paletteLines(tokens.dark)}
}

@media (prefers-color-scheme: dark) {
  .sarmg-theme[data-sarmg-theme="system"] {
    color-scheme: dark;
${paletteLines(tokens.dark)}
  }
}
`;
}

function sha256(content) {
  return createHash("sha256").update(content).digest("hex");
}

async function expectFile(path, expected) {
  let actual;
  try {
    actual = await readFile(path, "utf8");
  } catch {
    throw new Error(`generated file is missing: ${path}`);
  }
  if (actual !== expected) throw new Error(`generated file is stale: ${path}`);
}

async function writeAtomic(path, content) {
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.tmp`;
  await writeFile(temporary, content, { mode: 0o644 });
  await rename(temporary, path);
}

validateTokens(tokens);
const tokenCss = renderTokens();
const tokenCssPath = join(root, "design/web/tokens.css");
if (checkOnly) await expectFile(tokenCssPath, tokenCss);
else await writeAtomic(tokenCssPath, tokenCss);

const sourceNames = ["reset.css", "tokens.css", "content-card.css", "login.css", "accessibility.css"];
const sources = new Map();
for (const name of sourceNames) {
  sources.set(name, name === "tokens.css" ? tokenCss : await readFile(join(root, "design/web", name), "utf8"));
}

const bundle = sourceNames
  .map((name) => `/* sarmg-design:${name} */\n${sources.get(name).trim()}\n`)
  .join("\n");
const outputs = new Map([...sources, ["bundle.css", bundle]]);
const manifest = {
  schema_version: 1,
  package: "@sarmg/design",
  version: packageJson.version,
  author: packageJson.author,
  license: packageJson.license,
  source: "design/tokens/tokens.json",
  files: Object.fromEntries([...outputs].map(([name, content]) => [name, { sha256: sha256(content), bytes: Buffer.byteLength(content) }])),
};
const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
outputs.set("manifest.json", manifestText);
const checksums = [...outputs]
  .map(([name, content]) => `${sha256(content)}  ${name}`)
  .join("\n") + "\n";
outputs.set("SHA256SUMS", checksums);

const dist = join(root, "dist/design");
if (checkOnly) {
  for (const [name, content] of outputs) await expectFile(join(dist, name), content);
} else {
  const stage = `${dist}.stage`;
  await rm(stage, { recursive: true, force: true });
  await mkdir(stage, { recursive: true, mode: 0o755 });
  for (const [name, content] of outputs) await writeFile(join(stage, name), content, { mode: 0o644 });
  await rm(dist, { recursive: true, force: true });
  await rename(stage, dist);
}

process.stdout.write(`${checkOnly ? "verified" : "built"} @sarmg/design ${packageJson.version}\n`);
